FROM node:20-slim

WORKDIR /app

COPY package.json package-lock.json ./

RUN apt-get update && apt-get install -y openssl

RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]

# [Useful Commands]
# npm run dev -- -p 8080
# npm run build; npm run start -- -p 8080;
# tail -F anything
# pm2-runtime npm -- start
# /bin/bash